#!/bin/bash

mode="${MODE:-debug}"
binary="target/$mode/catbus"

$binary transport upload-index --file tmp/builds/3e9743acfb2781c1432f0811542d1f9bc0655aef-jessie-x86_64.tar --index tmp/builds/3e9743acfb2781c1432f0811542d1f9bc0655aef-jessie-x86_64.tar.idx | $binary transport receive-index --destination tmp/output --file 3e9743acfb2781c1432f0811542d1f9bc0655aef-jessie-x86_64.tar
